configName: pic32mx_eth_sk2
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MX795F512L
projectName: ''
settings:
  PackageFilter: azure_rtos;bootloader;bsp;core;csp;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MX_DFP\1.5.259
