configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-EF_DFP\1.3.58
