configName: pic32mk_gp_db
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_can;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_serial_memory;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-GP_DFP\1.5.130\atdf\PIC32MK1024GPE100.atdf
