format_version: v1.0
type: UniqueComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '41'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_MSD_DISK_IMAGE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: 'false'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '0x003C'}
  - type: Combo
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_SELECTION_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: usb_device_hid_bootloader}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: USB HID Bootloader}
- type: ElementPosition
  attributes: {x: '4', y: '204', id: usb_device}
