format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MK_MCM_Curiosity_Pro, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '262', y: '15', id: BSP_PIC32MK_MCM_Curiosity_Pro}
